---
- name: Setup the environment for development
  hosts: localhost
  vars_files:
      - vars.yml
  tasks:
      - name: Copy in template .env
        template:
            src: env.j2
            dest: .env
      - name: Create data directory
        ansible.builtin.file:
            path: data
            state: directory
            mode: '0755'
      - name: Create isochrone directory
        ansible.builtin.file:
            path: data/isochrone
            state: directory
            mode: '0755'
      - name: Create address json
        template:
            src: addresses.json.j2
            dest: data/isochrone/addresses.json
      - name: Create coordinates json
        template:
            src: coordinates.json.j2
            dest: data/isochrone/coordinates.json
