name: Scraper python package

on:
    push:
        paths:
            - 'scraper/**'
            - '.github/workflows/scraper-lint-and-test.yml'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build
              run: ./scraper/scripts/build.sh
