name: Scraper python package

on:
    push:
        paths:
            - 'scraper/**'
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Build
              run: docker build --tag scraperyyc --file docker/Dockerfile .
